# permissions for end users to edit idleoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: idleoperator-editor-role
rules:
- apiGroups:
  - cache.mickaelchau.fr
  resources:
  - idleoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.mickaelchau.fr
  resources:
  - idleoperators/status
  verbs:
  - get
