apiVersion: cache.mickaelchau.fr/v1alpha1
kind: IdleOperator
metadata:
  name: idleoperator-sample
spec:
  idle:
    - matchLabels:
      - app: label2c
      - app: label1d
      time: 0 17 * * 1-5
      duration: 10h