apiVersion: cache.mickaelchau.fr/v1alpha1
kind: IdleOperator
metadata:
  namespace: default
  name: idling-for-default
spec:
  idle:
    - matchLabels:
      - app: label1
      - tira: label2
      time: 0 8 * * 1-5
      duration: 3h
    - matchLabels:
      - app: label1
      time: 0 8 * * 1-5
      duration: 2h
    - matchLabels:
      - test: saucissed
      time: 0 8 * * 1-5
      duration: 0h