apiVersion: cache.mickaelchau.fr/v1alpha1
kind: IdleOperator
metadata:
  namespace: default
  name: idling-for-default
spec:
  idle:
    - matchLabels:
      - app: label1d
      - tira: label2d
      time: 0 8 * * 1-5
      duration: 19h
    - matchLabels:
      - app: label1x
      time: 0 8 * * 1-5
      duration: 19h
    - matchLabels:
      - test: saucissed
      time: 0 8 * * 1-5
      duration: 19h