apiVersion: apps/v1
kind: Deployment
metadata:
  name: toto
  namespace: default
  labels:
    app: label1
    tira: label2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: label1
      tira: label2
  template:
    metadata:
      labels:
        app: label1
        tira: label2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
