apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy4
  namespace: ttt
  labels:
    manger: froid
spec:
  replicas: 2
  selector:
    matchLabels:
      manger: froid
  template:
    metadata:
      labels:
        manger: froid
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
