apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausau
  namespace: ttt
  labels:
    test: saucisse
spec:
  replicas: 7
  selector:
    matchLabels:
      test: saucisse
  template:
    metadata:
      labels:
        test: saucisse
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

