apiVersion: cache.mickaelchau.fr/v1alpha1
kind: IdleOperator
metadata:
  namespace: ttt
  name: idling-for-ttt
spec:
  idle:
    - matchLabels:
      - app: label1
      - tira: label2
      time: 0* * 1-5
      duration: 10h
    - matchLabels:
      - app: label1cd
      time: 0 8 * * 1-5
      duration: xx
    - matchLabels:
      - test: saucisses
      time: 0 8 * * 1-5
      duration: 10h
    - matchLabels:
      - manger: froidx
      time: 0 8 * * 1-5
      duration: 10h