apiVersion: cache.mickaelchau.fr/v1alpha1
kind: IdleOperator
metadata:
  namespace: ttt
  name: idling-for-ttt
spec:
  idle:
    - matchLabels:
      - test: saucisse
      time: 0 8 * * 1-5
      duration: 2h
    - matchLabels:
      - manger: froid
      time: 0 8 * * 1-5
      duration: 2h